### ISSUE TITLE
Always-on-top css editor window

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/shelter-plugins#1]
Add a button to the css editor page which opens up an always-on-top window so that you can browse discord _and_ use the css editor at the same time.

**Comment by piotr25691** [comment]
also i might add a report to say that the last line in the css editor is clipped off

**Comment by SpikeHD** [comment]
@piotr25691 please make a separate issue for other bug reports please :)

**Comment by piotr25691** [comment]
> @piotr25691 please make a separate issue for other bug reports please :)

Ok, moving that
