### ISSUE TITLE
[Feature Request] Decor plugin port

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/shelter-plugins#21]
**Is your feature request related to a problem? Please describe.**
Currently the Decor plugin is only available for Vencord and Vandetta (afaik). 

**Describe the solution you'd like**
I would like to see a port of the Decor plugin to Shelter as well.

**Describe alternatives you've considered**
Make it Dorion only if Images needs to be fetched in a specific way, and it would be a lot of work to make for both Dorion and non Dorion clients.

**Additional context**
Decor is a plugin for Vencord that lets you add pfp decorations like what Discord started selling recently.
Currently the Vencord plugin does not work in Dorion due to images not working as intended.

**Comment by Temanor** [comment]
Now that Tauri Dorion v6 is out, this should work, right?

**Comment by SpikeHD** [comment]
It is possible but I don't really have an interest in Decor
