### ISSUE TITLE
[Feature Request] Message logger

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/shelter-plugins#22]
**Is your feature request related to a problem? Please describe.**
One of the most used plugins, Message logger, doesn't exist as a Shelter plugin :(

**Describe the solution you'd like**
Make a message logger for Shelter

**Describe alternatives you've considered**
Uhm... Don't do it?

**Additional context**
The user should be able to configure settings to set a limit for how many messages should be saved, and whitelist/blacklist feature.

**Comment by luximus-hunter** [comment]
This should be relatively easy I think? I'll look at the shelter dispatch evens later. Can't promise anything tho

**Comment by Temanor** [comment]
I think the settings for the plugin is what would need most work. It should be as configurable as possible.

**Comment by SpikeHD** [comment]
I do not intend to do this myself
