### ISSUE TITLE
[Feature Request] Allow zooming in and out in the app.

### ISSUE THREAD

**Issue by xemulat** [SpikeHD/shelter-plugins#24]
**Is your feature request related to a problem? Please describe.**
The feature is present in ArmCord.

**Describe the solution you'd like**
Allow zooming in and out using CTRL++ and CTRL+-.

**Describe alternatives you've considered**
No alternatives available.

**Additional context**
Nope.

**Comment by luximus-hunter** [comment]
You can zoom in and out the app in the dorion settings

**Comment by xemulat** [comment]
> You can zoom in and out the app in the dorion settings

Oh, thank you, I didn't see that.
