### ISSUE TITLE
[Feature Request] Social media link converter

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/shelter-plugins#25]
**Is your feature request related to a problem? Please describe.**
Social media platforms tends to break embeds, just like what happened with x (Twitter) recently.

**Describe the solution you'd like**
A plugin that converts Social media links to their respective modified formats for proper embedding when shared on Discord.

**Describe alternatives you've considered**
😶

**Additional context**
May add screenshots for this later.

**Comment by Temanor** [comment]
For example: twitter.com -> fxtwitter.com
tiktok -> vxtiktok
instagram -> ddinstgram

![image](https://github.com/SpikeHD/shelter-plugins/assets/91745601/37fda649-4017-4979-b1e9-01ae301efd30)

**Comment by Temanor** [comment]
There is also Bluesky, which I have never heard of, but their links would go from bsky -> bsyy

**Comment by Temanor** [comment]
It would be great if you could toggle which links it would convert and not.

**Comment by ioj4** [comment]
Is Yellowsink's [Text Replacements plugin](https://github.com/yellowsink/shelter-plugins) what you're looking for? You can configure your own RegEx patterns to replace your message content when it gets send. Or are you looking for a plugin that replaces the actual embed?
