### ISSUE TITLE
[Bug] Plugin Browser not working on Shelter MV2 v1.4

### ISSUE THREAD

**Issue by DeadLyBro** [SpikeHD/shelter-plugins#26]
**Describe the bug**
Plugin Browser not working on Shelter MV2 v1.4.
It give error: Uncaught (in promise) ReferenceError: localStorage is not defined.
```js
function U() {
            let e = localStorage.getItem("plugins-browser-cache"); // <-- here
```

**To Reproduce**
Install: Plugin Browser > Refresh: Page > Open: User Settings > Scroll down and click Plugin Browser. 
It dropped error on Console.

**Expected behavior**
Search and find Plugins on Github.

**Screenshots**
![image](https://github.com/SpikeHD/shelter-plugins/assets/31214077/43b531f4-74f8-4080-80f3-8e9228f5ac44)
![image](https://github.com/SpikeHD/shelter-plugins/assets/31214077/4c5b649a-c3ca-4139-b2b6-7c300344b2b1)
![image](https://github.com/SpikeHD/shelter-plugins/assets/31214077/2e68f0e6-f094-454f-b74e-568b6fc9140c)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Discord version: Stable/Web 288460 (c8280c6)
 - Any other relevant info: -

**Additional context**
-

**Comment by DeadLyBro** [comment]
+
Idk why, it worked before but now its not working at Shelter latest version. (MV3 v1.2)
bruh...

**Comment by SpikeHD** [comment]
This should hopefully be fixed in 8dca87e88fe5e126407916c21b9074679c9699fe, lemme know if it's still busted

**Comment by DeadLyBro** [comment]
![image](https://github.com/SpikeHD/shelter-plugins/assets/31214077/427d4f7d-bc30-465b-9642-bb9e4b491ae9)
![image](https://github.com/SpikeHD/shelter-plugins/assets/31214077/33112b11-9509-4e31-8d12-9e0baa1e9b6e)

Uh, when I press preview, it say you rate-limited.

```
documentation_url: "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
message: "API rate limit exceeded for IP ADRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
```

**Comment by SpikeHD** [comment]
This isn't an issue with the plugin, the GitHub API is just ratelimiting you. Try again in a little while and it should work.

**Comment by DeadLyBro** [comment]
> This isn't an issue with the plugin, the GitHub API is just ratelimiting you. Try again in a little while and it should work.

Ok, I will try some time later.
