### ISSUE TITLE
[Bug] Can't add custom games to ShelteRPC

### ISSUE THREAD

**Issue by maicol07** [SpikeHD/shelter-plugins#27]
**Describe the bug**
Error in console when pressing the add button in the add game dialog:
```
Uncaught TypeError: e.close is not a function
    at HTMLButtonElement.onClick [as $$click] (VencordWeb:20:32950)
    at HTMLDocument.Lr (VencordWeb:20:4357)
```

**To Reproduce**
1. Try to add a custom game

**Expected behavior**
Custom games gets added without any error

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 11
 - Discord version [e.g. Regular, Canary, PTB]: PTB
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Should be fixed in c772d3f3bd99d72be04a0df5c08996a67dc47322
