### ISSUE TITLE
[Bug] Plugin Browser doesn't work.

### ISSUE THREAD

**Issue by ImportTaste** [SpikeHD/shelter-plugins#28]
I tried Firefox ESR, Vivaldi, Edge, and an older browser that uses MV2. In all of them, I'm using the appropriate Shelter Injector extension, and in all of them, I would just get this popup error:

![image](https://github.com/SpikeHD/shelter-plugins/assets/53661808/929b49df-b768-4cc4-9e0c-3ef17c463597)

All of the errors in DevTools are related to the Access-Control-Allow-Origin not being present. Here's an example of an error from one of the browsers that is a bit more verbose than the ones from the other browsers:

Access to fetch at 'https://x1nto.github.io/shelter-shibblers/shelter-plugins//banger/plugin.json' from origin 'https://discord.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I'm on Windows 10. I'll provide more information as requested.

**Comment by SpikeHD** [comment]
Sounds like an issue with Shelter, and not this plugin. In theory it should [be removing the CSP header entirely](https://github.com/uwu/shelter/blob/b14c0dc805494f82adf085dc36666e0898759738/injectors/mv3/dnr-rules.json#L9). Maybe other headers need to be changed or something, but either way it's not really in the scope/control of the plugin itself.
