### ISSUE TITLE
Ivisible typing icon always showing

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/shelter-plugins#3]
The icon is still visible in channels you don't have permission to type, even though all other icons (including the one from the Vencord plugin) gets hidden.

![ZhGzHNf](https://github.com/SpikeHD/shelter-plugins/assets/91745601/bfcd99a9-52c5-4be3-aa73-de138b33e7de)

**Comment by SpikeHD** [comment]
Fixed in 6e99dc1
