### ISSUE TITLE
[Bug] Plugin Browser doesn't work.

### ISSUE THREAD

**Issue by samjaninf** [SpikeHD/shelter-plugins#30]
**Describe the bug**
Plugin browser has never worked for me, ever since I installed it a few months ago. And now it is giving an actual message telling me to look at dev console. But this isn't Canary. Do I need Canary for plugin browser to work?

**To Reproduce**
1. Install shelter.
2. Install Plugin Browser.
3. Go to plugin browser and observe empty list

**Expected behavior**
Describe what should be expected here.
Plugins should show up.

**Screenshots**
![image](https://github.com/SpikeHD/shelter-plugins/assets/6589200/a8ac85e7-61a1-4926-8356-352303bc6b62)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Discord version: Regular
 - Any other relevant info: It's never worked for me.

**Comment by SpikeHD** [comment]
You don't need Canary to look at the dev console, do you?

Even so, it would help alot to get those logs, so I'd ask that you try it on Canary to get them if that was the case

**Comment by samjaninf** [comment]
Thanks for the response but I genuinely thought you did. On the Discord support website they say it's only available on Canary and PTB. https://support.discord.com/hc/en-us/articles/115001239472-Troubleshooting-Console-Log-Errors

I would love to get you the console logs, If you could point me in the right direction. 🫡

**Comment by SpikeHD** [comment]
You will have to download Canary and install Shelter into that installation, and then send whatever errors (or just a screenshot) that are spat out from the console when accessing the plugin browser page.

**Comment by Milkshiift** [comment]
Just "Failed to fetch", same as the toast
![image](https://github.com/SpikeHD/shelter-plugins/assets/99212308/f9546f1e-3c51-4d35-944f-2385fd694658)

**Comment by Milkshiift** [comment]
Actually, maybe the Mixed Content errors are important. Fetch fails [here?](https://github.com/SpikeHD/shelter-plugins/blob/main/plugins/plugin-browser/github.ts#L39) and because it isn't handled everything blows up

**Comment by Milkshiift** [comment]
Made a pull request with a fix because why not https://github.com/SpikeHD/shelter-plugins/pull/32

**Comment by SpikeHD** [comment]
Thanks! @samjaninf can you confirm whether the plugin browser is working for you now?

**Comment by samjaninf** [comment]
Let me up date and I'll get back to you.
