### ISSUE TITLE
[Bug] Invisible typing tooltip doesn't behave like Vencord equivilant

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/shelter-plugins#34]
**Describe the bug**
The invisible typing tooltip that appears when hovering over the keyboard icon looks great in vanilla Discord, but if you use it together with Vencord plugins and have a theme, the invisible typing tooltip will not change the same way.

**To Reproduce**
Install the invisible typing shelter plugin.
Install Vencord or Equicord.
Install a Vencord/Equicord plugin like the "Send Timestamps" plugin.
Install a theme. For example Catppuccin Mocha.

**Expected behavior**
The tooltips should be themed in the same way as the Vencord plugins.
This would mean better consistency when using it together with Vencord plugins.

**Screenshots**

https://github.com/user-attachments/assets/4e29c69c-cf4e-41e8-bb6e-4660c1b79b36

**System Info**
 - OS: Windows 11
 - Discord version: Regular

**Additional context**
Additionally, invisible typing has a different animation for the tooltip, but I think I prefer this over the Vencord ones.

https://github.com/user-attachments/assets/b0b253a0-5b07-492d-ae6e-2c651bfa1a39

**Comment by SpikeHD** [comment]
This isn't really something in the scope of the plugin, its moreso to do Shelter itself, since the tooltip is a Shelter component.
