### ISSUE TITLE
[Feature Request] You're right but left

### ISSUE THREAD

**Issue by olivertzeng** [SpikeHD/shelter-plugins#37]
**Is your feature request related to a problem? Please describe.**
Yes, the problem was that inline code cannot be **read** and is horrible.

**Describe the solution you'd like**
To make inline code line to the left(maybe make it optional as well

**Describe alternatives you've considered**
no

**Additional context**
![圖片](https://github.com/user-attachments/assets/a7509716-465c-424a-aeaf-89aef433cca7)

**Comment by SpikeHD** [comment]
Maybe we should all start programming to the right from now on 🤔 

(fixed in 807bc3a4231fe59c79f1e7debb95d0f1c297c9c2)
