### ISSUE TITLE
[Bug] You're right acidentally flipped the whole text to the left

### ISSUE THREAD

**Issue by olivertzeng** [SpikeHD/shelter-plugins#38]
**Describe the bug**
Some of the texts are mirrored, like Da Vinci's notes.

**To Reproduce**
1. Reply to someone
2. See that the message is mirrored!

**Expected behavior**
To render the text correctly

**Screenshots**
Chinese version
![圖片](https://github.com/user-attachments/assets/d4293363-0c6d-470e-9da7-6cc00e94e403)
English version
![圖片](https://github.com/user-attachments/assets/698753d6-d74c-43c4-ab3b-af318688ee85)

**System Info (please complete the following information):**
 - OS: latest kernel version with Arch BTW
 - Discord version: Canary
 - Any other relevant info: I use Arch BTW and uses goofcord(with shelter + equicord)

**Comment by SpikeHD** [comment]
Should be fixed in da31b8f

**Comment by olivertzeng** [comment]
> Should be fixed in [da31b8f](https://github.com/SpikeHD/shelter-plugins/commit/da31b8fb303dd715faee3a2b7fd054fabe71419e)

Nice! Good to see this repo keeps updating!
