### ISSUE TITLE
[Bug] shelteRPC doesn't support http assets

### ISSUE THREAD

**Issue by wont-stream** [SpikeHD/shelter-plugins#41]
**Describe the bug**
Using a rich presence that uses external http assets causes the unknown asset icon.

**To Reproduce**
Use any rich presence that sets either key as an http link
Look at your profile

**Expected behavior**
Should do as the other shelter plugins do and handle external images.

**Screenshots**
![{631B25FB-3922-491F-90B1-880965E66ADD}](https://github.com/user-attachments/assets/5f794c71-256d-4813-8fb5-e44b5a676e8d)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Discord version: Canary
 - Any other relevant info: -

**Additional context**
\-

**Comment by SpikeHD** [comment]
Fixed in 3351a89c5648a40c4bd6d4a006ce040bddc67b03

![image](https://github.com/user-attachments/assets/3c2bda96-38bb-4360-8126-85b644646b61)
