### ISSUE TITLE
[Feature Request] ShelteRPC: Try to reconnect to server automatically

### ISSUE THREAD

**Issue by maicol07** [SpikeHD/shelter-plugins#42]
**Is your feature request related to a problem? Please describe.**
My arRPC server starts after shelteRPC, so I have to disable and reenable it manually 

**Describe the solution you'd like**
When shelteRPC can't connect to the server it retries after X seconds (it would be better if controlled with a setting) or wait the websocket (if possible)

**Describe alternatives you've considered**
Disable and reenable shelteRPC every time

**Comment by SpikeHD** [comment]
shelteRPC now features connection retry settings as of 868719b123a19881ce1a39bbc2053e898c918092, which should allow you to set a longer retry interval or larger retry count:

<img width="506" alt="image" src="https://github.com/user-attachments/assets/4d4579c7-ec84-4217-9bd3-38d6399f9f2e">

(The defaults are the same as they were previously)
