### ISSUE TITLE
[Bug] ShelteRPC: can't save settings

### ISSUE THREAD

**Issue by maicol07** [SpikeHD/shelter-plugins#43]
**Describe the bug**
When I edit settings it fails with this error in console:
```
Uncaught TypeError: t.onInput is not a function
 at o.$$input
 at HTMLDocument.Z1
```

**To Reproduce**
Install and enable ShelteRPC, try to configure settings

**Expected behavior**
Settings are saved

**Screenshots**

**System Info (please complete the following information):**
 - OS:  Windows 11
 - Discord version: PTB
 - Any other relevant info: Dorion 6.2.0

**Comment by SpikeHD** [comment]
Should be fixed as of 2cd65226b1fc5ea4317777d9036b1e6d45435bc2z
